### ISSUE TITLE
Script fails without indicating if anything was triggered or not

### ISSUE THREAD

**Issue by gijsk** [armenzg/mozilla_ci_tools#197] opened 2015-05-14 09:53 UTC
```
(virtualenv_) E:\dev\mozilla_ci_tools\mozci\scripts>python alltalos.py --times 14 --rev 188165e33ad0 --repo-name try
Please enter your full LDAP email address: gkruitbosch@mozilla.com
<snip -- the following is the first thing after I give my password and it gets stored:>
05/14/2015 10:49:29 INFO:        We want to trigger 'Rev5 MacOSX Yosemite 10.10 try talos chromez' on revision '188165e33ad0' a total of 14 time(s).
builds-2015-05-14.js: [>>>>>>>>>>>>>>>] Elapsed Time: 0:00:03   2.77 MB/s 8.0MB
Traceback (most recent call last):
  File "alltalos.py", line 93, in <module>
    main()
  File "alltalos.py", line 90, in main
    dry_run=options.dry_run)
  File "e:\dev\mozilla_ci_tools\mozci\mozci.py", line 343, in trigger_job
    buildername,
  File "e:\dev\mozilla_ci_tools\mozci\mozci.py", line 121, in _determine_trigger_objective
    status = buildapi.query_job_status(job)
  File "e:\dev\mozilla_ci_tools\mozci\sources\buildapi.py", line 153, in query_job_status
    req["request_id"])
  File "e:\dev\mozilla_ci_tools\mozci\sources\buildjson.py", line 152, in query_job_data
    job = _find_job(request_id, _fetch_data(filename), filename)
  File "e:\dev\mozilla_ci_tools\mozci\sources\buildjson.py", line 42, in _fetch_data
    json_contents = load_file(filepath, url)
  File "e:\dev\mozilla_ci_tools\mozci\utils\transfer.py", line 128, in load_file
    return _fetch_and_load_file(req, filepath)
  File "e:\dev\mozilla_ci_tools\mozci\utils\transfer.py", line 77, in _fetch_and_load_file
    shutil.move(temp_file.name, filename)
  File "e:\mozilla-build\python\Lib\shutil.py", line 303, in move
    os.unlink(src)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\gijs\\appdata\\local\\temp\\tmpzgwicc'
```

(I also don't understand what this error means and how I could fix it - to the best of my knowledge I'm not using the temp folder in question at all at the moment...)

**Comment by gijsk** [comment] 2015-05-14 10:03
Trying again produces:

```
(virtualenv_) E:\dev\mozilla_ci_tools\mozci\scripts>python alltalos.py --times 14 --rev 188165e33ad0 --repo-name try
05/14/2015 10:57:14 INFO:        We want to trigger 'Rev5 MacOSX Yosemite 10.10 try talos chromez' on revision '188165e33ad0' a total of 14 time(s).
Input Password:
05/14/2015 10:57:31 INFO:        There is a _build_ job that has completed successfully.
05/14/2015 10:57:31 INFO:        We have the necessary files to trigger the downstream job.
Traceback (most recent call last):
  File "alltalos.py", line 93, in <module>
    main()
  File "alltalos.py", line 90, in main
    dry_run=options.dry_run)
  File "e:\dev\mozilla_ci_tools\mozci\mozci.py", line 363, in trigger_job
    req = trigger(builder_to_trigger, revision, files, dry_run, extra_properties)
  File "e:\dev\mozilla_ci_tools\mozci\mozci.py", line 432, in trigger
    extra_properties)
  File "e:\dev\mozilla_ci_tools\mozci\sources\buildapi.py", line 63, in make_request
    content = req.json()
  File "e:\dev\mozilla_ci_tools\virtualenv_\lib\site-packages\requests-2.5.1-py2.7.egg\requests\models.py", line 799, in json
    return json.loads(self.text, **kwargs)
  File "e:\mozilla-build\python\Lib\json\__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "e:\mozilla-build\python\Lib\json\decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "e:\mozilla-build\python\Lib\json\decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Which is equally puzzling.

**Comment by vaibhavmagarwal** [comment] 2015-05-14 10:19
Looks like you are our first windows tester! Thanks for reporting this. I know that we download various build files for triggering and maybe that is hardcoded for unix environments. Will be looking into this.

In the meanwhile, if you have a mac or linux system, you can do 'sudo python setup.py develop' (virtualenv not necessary) to run it there.

**Comment by vaibhavmagarwal** [comment] 2015-05-14 16:31
Yes, I am able to reproduce this error. Looking into how I can solve it.

**Comment by armenzg** [comment] 2015-05-15 15:42
This is being fixed on https://github.com/armenzg/mozilla_ci_tools/pull/205

**Comment by vaibhavmagarwal** [comment] 2015-05-18 09:18
With the latest release, this error should be fixed. Closing it.

**Closed by vaibhavmagarwal** 2015-05-18 09:18 UTC
Labels: bug
